import {
  IconAirConditional,
  IconBbq,
  IconCampBed,
  IconCampShower,
  IconCampSink,
  IconCampWifi,
  IconCooking,
  IconElectricity,
  IconExercise,
  IconHeating,
  IconPersonalShower,
  IconPlay,
  IconPublicToilet,
  IconRestRoom,
  IconStore,
  IconTrampoline,
  IconWalkingPath,
  IconWaterPlay,
} from '@/public/svgs';

const AMENITIES_CONFIG = [
  { image: <IconStore />, buttonText: '매점' },
  { image: <IconPersonalShower />, buttonText: '개인샤워실' },
  { image: <IconRestRoom />, buttonText: '개인화장실' },
  { image: <IconBbq />, buttonText: '바베큐' },
  { image: <IconAirConditional />, buttonText: '에어컨' },
  { image: <IconCampWifi />, buttonText: '와이파이' },
  { image: <IconTrampoline />, buttonText: '트램플린' },
  { image: <IconCampSink />, buttonText: '개수대' },
  { image: <IconPlay />, buttonText: '놀이시설' },
  { image: <IconCampShower />, buttonText: '샤워실' },
  { image: <IconPublicToilet />, buttonText: '화장실' },
  { image: <IconCampWifi />, buttonText: 'TV' },
  { image: <IconHeating />, buttonText: '난방기구' },
  { image: <IconWaterPlay />, buttonText: '물놀이' },
  { image: <IconWalkingPath />, buttonText: '산책로' },
  { image: <IconExercise />, buttonText: '운동시설' },
  { image: <IconElectricity />, buttonText: '전기' },
  { image: <IconCooking />, buttonText: '취사도구' },
  { image: <IconCampBed />, buttonText: '침대' },
];

export default AMENITIES_CONFIG;
